-- Postgres schema for the VBSPU department dashboard.
-- Generated by scripts/import-excel-data.ts — regenerate with: npm run import:excel
--
-- GROUNDWORK ONLY: nothing in the app connects to Supabase yet. This mirrors
-- the TypeScript model in data/types.ts 1:1 so the current data/imported JSON
-- can be loaded without reshaping when that phase starts.
--
-- Nullability follows the source: every column fed by a spreadsheet cell is
-- nullable, because any of them can be blank in the workbooks. Only generated
-- identity columns and the names records are keyed by are NOT NULL. A blank
-- cell and a real 0 are different facts, so no column carries a DEFAULT that
-- would turn one into the other.

-- Ids are the slugs the importer derives from the source (e.g. 'cse-and-it',
-- 'cse-and-it-f3'), so they stay stable and human-readable across re-imports.

CREATE TABLE IF NOT EXISTS departments (
  id                      text PRIMARY KEY,
  faculty_of_engineering  text,
  name                    text NOT NULL,
  short_name              text NOT NULL,
  dean_name               text,
  hod_name                text,
  hod_contact             text,
  reporting_period        text,
  date_of_submission      text,
  -- True when the workbook named no department and the name came from its filename.
  name_from_filename      boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS programs (
  id                              text PRIMARY KEY,
  dept_id                         text NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  s_no                            integer NOT NULL,
  name                            text NOT NULL,
  year_of_commencement            integer,
  -- Free text: some workbooks put a programme name in this column.
  mode_of_programme               text,
  sanctioned_professor            integer,
  sanctioned_associate_professor  integer,
  sanctioned_assistant_professor  integer,
  semester_fee_2024               numeric,
  semester_fee_2025               numeric,
  semester_fee_2026               numeric,
  sanctioned_intake_2024          integer,
  sanctioned_intake_2025          integer,
  sanctioned_intake_2026          integer,
  admitted_2024                   integer,
  admitted_2025                   integer,
  admitted_2026                   integer,
  nep_aligned                     boolean,
  multiple_entry_exit             boolean,
  internship_end_of_year          boolean,
  minor_specialisation_available  boolean,
  remarks                         text
);
CREATE INDEX IF NOT EXISTS programs_dept_id_idx ON programs(dept_id);

CREATE TABLE IF NOT EXISTS faculty (
  id                          text PRIMARY KEY,
  dept_id                     text NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  s_no                        integer NOT NULL,
  name                        text NOT NULL,
  designation                 text,
  appointment_type            text,
  -- ISO yyyy-mm-dd where the cell parsed as a date, else the original text,
  -- so an unparseable date is preserved rather than dropped.
  date_of_joining             text,
  -- Null where the cell said something other than Yes/No (e.g. "Persuing").
  has_phd                     boolean,
  programmes_appointed_for    text,
  teaching_load_hrs_per_week  numeric,
  additional_responsibility   text
);
CREATE INDEX IF NOT EXISTS faculty_dept_id_idx ON faculty(dept_id);

-- A person can serve several departments. faculty.dept_id is the PRIMARY
-- department (breadcrumb routing); every department served, primary included,
-- is a row here. Dept-level counts join through this table; university-wide
-- totals count DISTINCT faculty.id.
CREATE TABLE IF NOT EXISTS faculty_departments (
  faculty_id  text NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  dept_id     text NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  PRIMARY KEY (faculty_id, dept_id)
);

-- One research record per faculty member (1—1).
CREATE TABLE IF NOT EXISTS faculty_research (
  id                         text PRIMARY KEY,
  faculty_id                 text NOT NULL UNIQUE REFERENCES faculty(id) ON DELETE CASCADE,
  journal_sci_scie_ssci      integer,
  journal_scopus_ugc_care    integer,
  journal_other              integer,
  conference_international   integer,
  conference_national        integer,
  h_index                    integer,
  i10_index                  integer,
  google_scholar_orcid_link  text,
  patents_filed              integer,
  patents_published          integer,
  patents_granted            integer,
  phd_registered             integer,
  phd_awarded                integer
);

-- Many projects per faculty member (1—many).
CREATE TABLE IF NOT EXISTS faculty_projects (
  id                 text PRIMARY KEY,
  faculty_id         text NOT NULL REFERENCES faculty(id) ON DELETE CASCADE,
  sponsoring_agency  text,
  year_of_grant      integer,
  -- Free text: "3 Year", "Upto March 2028", "Co-PI with …" all occur.
  duration           text,
  -- Rupees. Null where the cell held something unquantifiable ("Beam Time").
  sanctioned_amount  numeric,
  amount_released    numeric,
  current_status     text
);
CREATE INDEX IF NOT EXISTS faculty_projects_faculty_id_idx ON faculty_projects(faculty_id);

CREATE TABLE IF NOT EXISTS infrastructure (
  id                            text PRIMARY KEY,
  dept_id                       text NOT NULL REFERENCES departments(id) ON DELETE CASCADE,
  s_no                          integer NOT NULL,
  lab_classroom_name            text,
  floor_room_no                 text,
  hours_allotted_per_week       numeric,
  -- Department-level figure from the sheet header, repeated on each row.
  current_weekly_working_hours  numeric,
  lab_room_in_charge            text,
  lab_assistant_support_staff   text,
  student_capacity              integer,
  major_equipment_available     text,
  programmes_using_facility     text,
  utilisation_pct               numeric,
  digital_smart_board           boolean,
  projector                     boolean
);
CREATE INDEX IF NOT EXISTS infrastructure_dept_id_idx ON infrastructure(dept_id);

-- One submission record per department (1—1).
CREATE TABLE IF NOT EXISTS hod_submissions (
  dept_id                                 text PRIMARY KEY REFERENCES departments(id) ON DELETE CASCADE,
  mobile_contact                          text,
  date_of_submission                      text,
  -- Snapshot figures as reported on the sheet, not recomputed from the rows.
  snapshot_no_of_programmes               integer,
  snapshot_total_faculty_reported         integer,
  snapshot_total_sanctioned_intake_2026   integer,
  snapshot_faculty_with_phd               integer,
  snapshot_total_students_admitted_2026   integer,
  snapshot_labs_classrooms_reported       integer,
  snapshot_programmes_with_nep_alignment  integer,
  snapshot_digital_smart_board_available  integer,
  snapshot_projector_available            integer,
  certification_signed_by                 text,
  certification_date                      text,
  status                                  text NOT NULL
    CHECK (status IN ('Submitted', 'Pending', 'Partial'))
);

-- One department-level target summary per department (1—1).
CREATE TABLE IF NOT EXISTS faculty_target_summaries (
  dept_id                              text PRIMARY KEY REFERENCES departments(id) ON DELETE CASCADE,
  review_period                        text,
  total_faculty_planned                integer,
  journal_publication_target           integer,
  conference_paper_target              integer,
  sponsored_industry_proposals_target  integer,
  target_funding_lakh                  numeric,
  patent_filing_target                 integer,
  avg_milestone_achievement            numeric
);

-- One annual target sheet per faculty member (1—1).
CREATE TABLE IF NOT EXISTS faculty_targets (
  id                                                text PRIMARY KEY,
  faculty_id                                        text NOT NULL UNIQUE REFERENCES faculty(id) ON DELETE CASCADE,
  s_no                                              integer NOT NULL,
  designation                                       text,
  nature_of_appointment                             text,
  date_of_joining                                   text,
  review_period                                     text,
  sci_scie_ssci_journal_papers                      integer,
  scopus_ugc_care_journal_papers                    integer,
  q1q2_journal_papers_subset                        integer,
  international_conference_papers                   integer,
  national_conference_papers                        integer,
  govt_sponsored_project_proposals                  integer,
  industry_project_proposals                        integer,
  target_funding_lakh                               numeric,
  funding_agencies_targeted                         text,
  tentative_project_theme_title                     text,
  target_submission_month                           text,
  consultancy_industry_assignment_proposals         integer,
  patents_to_be_filed                               integer,
  patents_expected_published                        integer,
  patents_expected_granted                          integer,
  prototype_product_technology_proposed             text,
  new_revised_course_syllabus_or_lab                text,
  e_content_mooc_innovative_teaching                text,
  student_mentoring_hackathon_internship_placement  text,
  contribution_to_dept_development                  text,
  contribution_to_university_development            text,
  expected_measurable_outcome_by_june_2027          text,
  q1_plan                                           text,
  q2_plan                                           text,
  q3_plan                                           text,
  q4_plan                                           text,
  -- Free text, not an enum: the workbooks hold "--", "Achive" and whole
  -- sentences in these cells alongside the expected statuses.
  q1_status                                         text,
  q2_status                                         text,
  q3_status                                         text,
  q4_status                                         text,
  milestone_achievement_pct                         numeric,
  hod_priority                                      text,
  hod_remarks_support_required                      text,
  year_end_achievement_summary                      text
);
CREATE INDEX IF NOT EXISTS faculty_targets_faculty_id_idx ON faculty_targets(faculty_id);
